version: 3.400 - Preview{build}
branches:
  only:
  - main
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- cmd: dotnet publish -p:PublishProfile=FolderProfile
artifacts:
- path: bin\Release\net6.0-windows\publish\win-x86\CloudClassUtility.exe
  name: CloudClassUtility
deploy:
- provider: GitHub
  tag: 034$(APPVEYOR_BUILD_NUMBER)
  release: v$(appveyor_build_version)
  auth_token:
    secure: w0Rgb7Q7p2t6sAWtWcf5y76IXQoFP0HaKLNKU3ABOuFBS0bHh+tKE12NFT4IxOi9
  repository: Cookie987/CloudClassUtility
  artifact: CloudClassUtility
  draft: true
  prerelease: true
  force_update: true