version: 3.400 - Preview{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- cmd: dotnet publish -p:PublishProfile=FolderProfile
artifacts:
- path: bin\Release\net6.0-windows\publish\win-x86\CloudClassUtility.exe
  name: CloudClassUtility