version: Preview 22w{build}a
branches:
  only:
  - main
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- cmd: dotnet publish -p:PublishProfile=FolderProfile
artifacts:
- path: bin\Release\net6.0-windows\publish\win-x86\CloudClassUtility.exe
  name: CloudClassUtility
#deploy:
#- provider: GitHub
#  tag: 22w$(APPVEYOR_BUILD_NUMBER)a
#  release: $(appveyor_build_version)
#  auth_token:
#    secure: w0Rgb7Q7p2t6sAWtWcf5y76IXQoFP0HaKLNKU3ABOuFBS0bHh+tKE12NFT4IxOi9
#  repository: Cookie987/CloudClassUtility
#  artifact: CloudClassUtility
#  draft: true
#  prerelease: true
#  force_update: true